### ISSUE TITLE
Error while connecting to Drachtio Server

### ISSUE THREAD

**Issue by shaibiii9777** [davehorton/drachtio-server#101]
Hi, 
I am using Docker Image to run Drachtio Server by the following command
docker pull drachtio/drachtio-server:latest
after adding image I run the image using name:tag 

Now when I try to connect to drachtio server from my node application using 'drachtio-srf' package
with following configuration 

const Srf = require('drachtio-srf');
const srf = new Srf();
srf.connect({
"host": "127.0.0.1",
"port": 9022,
 "secret": "cymru"
});

I get the following error

{"level":50,"time":1571690489862,"pid":18227,"hostname":"Shaibiii-HP-Probook","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9022,"msg":"connect ECONNREFUSED 127.0.0.1:9022","stack":"Error: connect ECONNREFUSED 127.0.0.1:9022\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)","type":"Error","v":1}

**Comment by davehorton** [comment]
Your drachtio app is trying to connect to localhost (127.0.0.1) port 9022, and failing, so we can infer that nothing is listening on that port.

You say you are running the drachtio server in a docker container.  Are you running with host networking mode ?  I'm guessing not, and that is your problem.

**Comment by shaibiii9777** [comment]
> Your drachtio app is trying to connect to localhost (127.0.0.1) port 9022, and failing, so we can infer that nothing is listening on that port.
> 
> You say you are running the drachtio server in a docker container. Are you running with host networking mode ? I'm guessing not, and that is your problem.

I will look upon it, I also tried the through source build, but it gives couple of error although i tried it step by step, was stuck on "./bootstrap.sh file not found while trying to install sofia-sip" is there any error guide?

**Comment by shaibiii9777** [comment]
> Your drachtio app is trying to connect to localhost (127.0.0.1) port 9022, and failing, so we can infer that nothing is listening on that port.
> 
> You say you are running the drachtio server in a docker container. Are you running with host networking mode ? I'm guessing not, and that is your problem.

So pulled image of 'nginx' and running on port 80, checked from browser, Running Drachtio server from docker, but node still refused to connect with following error



Error: connect ECONNREFUSED 127.0.0.1:9022
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
at Immediate.setImmediate (/home/shaibiii/Documents/Project/node_modules/drachtio-srf/lib/srf.js:60:64)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)

nginx is running at port 80, so i changed configuration of drachtio-srf to following
const Srf = require('drachtio-srf');
const srf = new Srf();
srf.connect({
"host": "127.0.0.1",
"port": 80,
"secret": "cymru"
});

and got 400 error code with error message "invalid message from server, did not start with length specifier: HTTP/1.1 400 Bad Request
Server: nginx/1.17.4"

Sorry for any blunder, i am new to drachtio

**Comment by shaibiii9777** [comment]
Got it fixed, was not adding IP lookup between Docker and Windows .. Added docker IP range in Windows IP lookup, Now i can access Drachtio Container using Container IP

**Comment by davehorton** [comment]
can we close this issue now?

BTW, as to the problem you had building from source, it seems you forgot to do this after cloning the repo:

```
git submodule update --init --recursive
```

**Comment by shaibiii9777** [comment]
I ran that command, basically faced different issue everytime i tried to build from source, got libtool version issue although latest version was installed, and sometime bootstrap.sh issue

and yes, can close this issue now,

**Comment by davehorton** [comment]
what linux distro are you using, and what branch of drachtio server are you trying to build?

**Comment by prawee** [comment]
me too.
