### ISSUE TITLE
Issue connecting to Drachtio Server

### ISSUE THREAD

**Issue by aid-don** [davehorton/drachtio-server#107]
Hi Dave,
(Thanks for the app :+1: ) We're trying to setup Drachtio to redirect all SIP traffic to another server using 301. (Think it will be possible with your code?)

Anyhow I have drachtio-server installed from source on a digitalocean droplet. Have included default config and service installed and running ok. There is also no firewall on the server. We are using Debian 9 for this server.

From another server where I want to run drachtio-srf we have installed node and app as per instructions but cant start app. get below error.

`[root@sip01 dractio]# node app.js `
`
/var/lib/dractio/app.js:10
srf.on('connect', (err, hostport) => {
                                   ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3`

Also to confirm connectivity I can telnet to port 9022 ok from node machine to drachtio-server. I have also tried changing the the port to 9021 on both sides to no avail. So I know that connectivity is ok. Also I have verified secret as well.

`[root@sip01 dractio]# node --version
v0.10.30
`

Would you have any pointers?

KR,
Aiden

**Comment by davehorton** [comment]
I'm not  sure if that version of node supports ES6.  It seems to have some issue with the '=>' function notation. Can you install v10.16.0 of node and try again?

I typically run this ansible role on my servers to install node.js

https://github.com/davehorton/ansible-role-nodejs

**Comment by aid-don** [comment]
Thanks Dave. Will try that and let you know.
