### ISSUE TITLE
large sip message  crash

### ISSUE THREAD

**Issue by ChungTak** [davehorton/drachtio-server#85]
when send large sip message to drachtio
```2019-06-17 23:07:36.127568 recv 1323 bytes from udp/[192.168.111.160]:5060 at 23:07:36.127426:
MESSAGE sip:34020000002000000002@192.168.111.32:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.111.160:5060;rport;branch=z9hG4bK124575361
From: <sip:34020000001320000001@192.168.111.160:5060>;tag=340678427
To: <sip:34020000002000000002@192.168.111.32:5060>
Call-ID: 187588490@192.168.111.160
CSeq: 20 MESSAGE
Max-Forwards: 70
User-Agent: SIP UAS V2.1.4.500306
Content-Type: Application/MANSCDP+xml
Content-Length:   900

<?xml version="1.0" encoding="GB2312" ?>
<Response>
<CmdType>Catalog</CmdType>
<SN>1</SN>
<DeviceID>34020000001320000001</DeviceID>
<SumNum>1</SumNum>
<DeviceList Num="1">
<Item>
<DeviceID>34020000001310000001</DeviceID>
<Name></Name>
<Manufacturer>Dahua</Manufacturer>
<Model>IPC-HFW3236M-I1</Model>
<Owner>0</Owner>
<CivilCode>340200</CivilCode>
<Address>axy</Address>
<Parental>0</Parental>
<ParentID>34020000001320000001</ParentID>
<RegisterWay>1</RegisterWay>
<Secrecy>0</Secrecy>
<StreamNum>2</StreamNum>
<Status>ON</Status>
<Info>
<PTZType>3</PTZType>
<DownloadSpeed>1/2/4/8</DownloadSpeed>
</Info>
</Item>
</DeviceList>
</Response>
```
 get error  
 
```
D:\MyProject\node_modules\drachtio-srf\lib\drachtio-agent.js:762
        throw new Error('unexpected message with type: ' + token[1]) ;
        ^
Error: unexpected message with type: undefined
    at DrachtioAgent._onMsg (D:\MyProject\node_modules\drachtio-srf\lib\drachtio-agent.js:762:15)
    at WireProtocol.emit (events.js:182:13)
    at WireProtocol.processMessageBuffer (D:\MyProject\node_modules\drachtio-srf\lib\wire-protocol.js:270:12)
    at WireProtocol._onData (D:\MyProject\node_modules\drachtio-srf\lib\wire-protocol.js:304:14)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by davehorton** [comment]
thx, which version of drachtio-srf are you using?

**Comment by ChungTak** [comment]
drachtio-srf 4.4.8 
we use drachtio-srf  receive  sip message.
```
srf.message((req, res) => {
    console.log(`connected message ${req.body}`);
    res.send(200);
});
```
small sip message is ok.
large sip message get error. we found "wire-protocol.js" -> method  processMessageBuffer . line271:
```
obj.incomingMsg = [...obj.incomingMsg].slice(start + length).join('');
```
obj.incomingMsg = '0#xxxxxxxxx'
the length == 0 . case this issue

**Comment by davehorton** [comment]
I'm having trouble recreating the issue, and I am trying to send the same message.

One thing that seems strange: in your message above Content-Length is 900.  When I test with that exact message, the calculated Content-Length is only 668.  It seems that your client may be putting an incorrect value in the Content-Length header, is that possible?

```
2019-06-18 07:55:05.375769 recv 1075 bytes from udp/[127.0.0.1]:5060 at 07:55:05.375580:
MESSAGE sip:34020000002000000002@127.0.0.1:5090 SIP/2.0^M
Via: SIP/2.0/UDP 192.168.111.160:5060;rport;branch=z9hG4bK124575361^M
From: <sip:34020000001320000001@192.168.111.160:5060>;tag=340678427^M
To: <sip:34020000002000000002@127.0.0.1:5090>^M
Call-ID: 1-6091@172.20.20.20^M
CSeq: 20 MESSAGE^M
Max-Forwards: 70^M
User-Agent: SIP UAS V2.1.4.500306^M
Content-Type: Application/MANSCDP+xml^M
Content-Length:   668^M
^M
<?xml version="1.0" encoding="GB2312" ?>^M
<Response>^M
<CmdType>Catalog</CmdType>^M
<SN>1</SN>^M
<DeviceID>34020000001320000001</DeviceID>^M
<SumNum>1</SumNum>^M
<DeviceList Num="1">^M
<Item>^M
<DeviceID>34020000001310000001</DeviceID>^M
<Name></Name>^M
<Manufacturer>Dahua</Manufacturer>^M
<Model>IPC-HFW3236M-I1</Model>^M
<Owner>0</Owner>^M
<CivilCode>340200</CivilCode>^M
<Address>axy</Address>^M
<Parental>0</Parental>^M
<ParentID>34020000001320000001</ParentID>^M
<RegisterWay>1</RegisterWay>^M
<Secrecy>0</Secrecy>^M
<StreamNum>2</StreamNum>^M
<Status>ON</Status>^M
<Info>^M
<PTZType>3</PTZType>^M
<DownloadSpeed>1/2/4/8</DownloadSpeed>^M
</Info>^M
</Item>^M
</DeviceList>^M
</Response>
```

Please create a gist of the drachtio server log, with loglevel set to debug and post it

**Comment by ChungTak** [comment]
[drachtio.log](https://gist.github.com/ChungTak/d5327d0cbefacb2c7b5b6a3dca3b4cba)
```
<DeviceID>34020000001310000001</DeviceID>
<Name>²Ö¿â²àÃÅ</Name>
```
message has unreadable codes. the message  use  GB2312 encoding.

**Comment by davehorton** [comment]
Yes, we only support utf-8 encoding at the moment.  I'm pretty sure that is the issue.
